config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'

  resources :sessions, only: [:index, :new, :create, :destroy]
  resources :projects
  resources :users, only: [:new, :create] do
    resources :messages
    resources :projects do
      resources :rewards
    end
    resources :pledges do
      resources :projects, only: [:show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :pledges
  has_many :users, through: :pledges
  has_many :rewards, inverse_of: :project
  has_many :tags, inverse_of: :project
  accepts_nested_attributes_for :rewards, allow_destroy: true
  accepts_nested_attributes_for :tags, allow_destroy: true

  validates :startdate, presence: true
  validates :finishdate, presence: true
  validate :project_finishdate_larger_than_current_date, :project_startdate_larger_than_current_date, :startdate_earlier_than_finishdate;

  def project_finishdate_larger_than_current_date
    if finishdate.present? && finishdate < Date.today
      errors.add(:enddate, "Selected date must be larger than current date")
   end
  end

  def project_startdate_larger_than_current_date
      if startdate.present? && startdate < Date.today
        errors.add(:startdate, "Selected date must be larger than current date")
     end
  end

  def startdate_earlier_than_finishdate
    if finishdate.present? && startdate.present? && finishdate < startdate
      errors.add(:datecompare, "End date must be after start date")
    end
  end

end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :project
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  has_many :owned_projects, class_name: "Project"
  has_many :messages
  has_many :pledges
  has_many :projects, through: :pledges
  has_many :rewards, through: :projects
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Log in, please"
      redirect_to new_session_url
    end
  end

  helper_method :current_user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.all
  end

  def create
    @types = ['user', 'project'];
    @message = Message.new
    @message.user_id = current_user.id
    if current_user && params["projectinfo"]
      @message.infomation = params["infomation"]
      @message.messagetoid = params["projectinfo"]
      @message.messagetotype = @types[1]
    elsif current_user && params["userinfo"]
      @message.infomation = params["infomation"]
      @message.messagetoid = params["userinfo"]
      @message.messagetotype = @types[0]
    end

    if @message.save!
      respond_to do |format|
        format.html
        format.json{render 'json': @message}
      end
    else
      render :new
    end
  end

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
  def index
    @pledges = Pledge.all
  end

  def create
    @pledge = Pledge.new
    @pledge.user_id = current_user.id
    @pledge.project_id = params['project']
    @pledge.amount = Reward.find(params['reward']).price

    puts @pledge.project_id
    if @pledge.save!
      respond_to do |format|
        format.html
        format.json
      end
    else
      render :index
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @categories = Category.all
    @tags = Tag.all
    @projects = Project.all
    @pledges = Pledge.all
    @rewards = Reward.all
    if current_user
      @messages = Message.where(messagetoid: current_user.id, messagetotype: 'user');
    end
    @availableprojects = {}
    @fitprojects = []


    if params["taginfo"]
      @tags.where("title LIKE ?", "%#{params["taginfo"]}%").each do |tag|
        @fitprojects << tag.project_id
      end
    end
    @fitprojects.uniq!
    @matchprojects = Project.find(@fitprojects)




    if current_user
      if @matchprojects && params["taginfo"]
        @matchprojects.each do |matproject|
          if current_user.pledges.exists?(project_id: matproject.id)
            @availableprojects[matproject.id] = 'true'
          else
            @availableprojects[matproject.id] = 'false'
          end
        end
      else
        @projects.each do |project|
          if current_user.pledges.exists?(project_id: project.id)
            @availableprojects[project.id] = 'true'
          else
            @availableprojects[project.id] = 'false'
          end
        end
      end


    end

    respond_to do |format|
      format.html
      if current_user && params["category"] == 'all'
        response = {:projectinfo => @projects.where.not(user_id: current_user.id), :pledgedinfo => @availableprojects}
        format.json {render json: response}
      elsif current_user && params["taginfo"]
        response = {:projectinfo => @matchprojects.delete_if{|matchproject|matchproject.user_id == current_user.id},:pledgedinfo => @availableprojects}
        format.json {render json: response}
      elsif current_user
        response = {:projectinfo => @projects.where(category_id: params["category"]).where.not(user_id: current_user.id), :pledgedinfo => @availableprojects}
        format.json {render json: response}
      elsif params["category"] == 'all'
        response = {:projectinfo => @projects, :pledgedinfo => @availableprojects}
        format.json {render json: response}
      elsif params["taginfo"]
        response = {:projectinfo => @matchprojects,:pledgedinfo => @availableprojects}
        format.json {render json: response}
      else
        response = {:projectinfo => @projects.where(category_id: params["category"]), :pledgedinfo => @availableprojects}
        format.json {render json: response}
      end
    end

  end


  def show
    @project = Project.find(params[:id])
    puts @project.id

    @messagesprojects = Message.where(messagetoid: @project.id, messagetotype: 'project')
    puts @messagesprojects
  end

  def new
    @project = Project.new
    @project.rewards.build
    @project.tags.build

    @reward = Reward.new
    @category = Category.all
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    if @project.save
      redirect_to root_url
    else
      @category = Category.all
      flash[:notice] = "Must enter valid date"
      render :new
    end
  end


  private

  def project_params
    params.require(:project).permit(:title, :description, :startdate,
    :finishdate, :goal,:category_id, rewards_attributes:
    [:description, :price, :_destroy],
    tags_attributes:[:title, :_destroy])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index

  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In!"
    else
      flash.now[:alert] = "Invalid user email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end


private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Crowdfunder</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/heroic-features.css" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
      <% end %>

      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
             <div class="navbar-header">
                <a class="navbar-brand" href="/">Home</a>
            </div>
             <div class="collapse navbar-collapse" >
                <ul class="nav navbar-nav">
                  <% if current_user %>
                  <li>
                  <%= link_to "New Project", new_user_project_path(current_user.id)%>
                  </li>
                  <li>
                  <%= link_to "Log Out", session_path("current"), :method => :delete, class: "logout"%>
                  </li>
                  <% else %>
                  <li>
                    <%= link_to "Log In", new_session_path, class: "login"%>
                  </li>
                  <li>
                    <%= link_to "Sign Up", new_user_path, class:"signup" %>
                  </li>
                 <% end %>
                </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

  </header>
  <br>
  <br>
  <div>
    <% if current_user %>
    Hello, <%= current_user.name %>!
    <% end %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for ([@user, @project]) do |f| %>
    <fieldset>
    <div class="form-group">
      <%= f.label :title %></br>
      <%= f.text_field :title %>
    </div>

    <div class="form-group">
      <%= f.label :description %></br>
      <%= f.text_area :description %>
    </div>

    <div class="form-group">
      <%= f.label :startdate %></br>
      <%= f.datetime_field :startdate %>
    </div>

    <div class="form-group">
      <%= f.label :finishdate %></br>
      <%= f.datetime_field :finishdate %>
    </div>

    <div class="form-group">
      <%= f.label :goal %></br>
      <%= f.number_field :goal %>
    </div>

    <div class="form-group">
      <%= f.label :category %></br>
      <%= f.select(:category_id) do %>
        <%= @category.each do |content| %>
          <%= content_tag(:option, content.title, value: content.id) %>
        <% end %>
      <% end %>
    </div>
    </fieldset>

    <h3>Tags</h3>
      <div id="tags">
        <%= f.fields_for :tags do |tag| %>
          <%= render 'tag_fields', :f => tag %>
        <% end %>
        <div class="links">
          <%= link_to_add_association 'add tag', f, :tags %>
        </div>
      </div>


    <h3>Rewards</h3>
    <div id="rewards">
      <%= f.fields_for :rewards do |reward| %>
        <%= render 'reward_fields', :f => reward %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add reward', f, :rewards %>
      </div>
    </div>

  </br>
  <div id="project_button">
  <%= f.submit %>
  </div>
<% end %>

app/views/projects/_reward_fields.html.erb
<div class="nested-fields">
  <fieldset>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :price %>
      <%= f.number_field :price %>
    </div>
    <%= link_to_remove_association "remove reward", f %>
  </fieldset>
</div>

app/views/projects/_tag_fields.html.erb
<div class="nested-fields">
  <fieldset>
    <div class="form-group">
      <%= f.label :title  %>
      <%= f.text_area :title %>
    </div>
    <%= link_to_remove_association "remove tag", f %>
  </fieldset>
</div>

app/views/projects/index.html.erb
<br>
<div class="categorybuttons">
  <button clsss= "category" type="button" name="button" value="">All</button><bn>
  <% @categories.each do |category| %>
    <button clsss= "category" type="button" name="button" value="<%= category.id %>"><%= category.title.capitalize %></button><bn>
  <% end %>
</div>
<br>
<form id="searchbar" action="/html" method="post">
  <label for="q">Search Tag:</label>
  <input id="q" name="q" type="text" />
  <input name="commit" type="submit" value="Search">
</form>

<br>
<br>
<div class="projects">
  <% @projects.each do |project| %>
    <% if current_user && project.user_id != current_user.id%>
      <a href="http://localhost:3000/projects/<%= project.id %>"><%= project.title %></a>
      <% if current_user.pledges.exists?(project_id: project.id) %>
        <p>you backed this project</p>
      <% end %>
      <p><%= project.description %></p>
    <% elsif !current_user %>
      <a href="http://localhost:3000/projects/<%= project.id %>"><%= project.title %></a>
      <p><%= project.description %></p>
    <% end %>
  <% end %>
</div>
<br>

<% if current_user %>
  </br>
  <h3>My Projects</h3>
  <% @projects.each do |project| %>
   <% if project.user_id == current_user.id %>
      <p class="ptitle"><%= link_to project.title, project %></p>
      <p class="pdescription"><%= project.description %></p>
   <% end %>
  <% end %>
  <h3>My Messages</h3>
  <div class="mymessage">
    <% @messages.each do |message| %>
      <p>From: <%= message.user.name %></p>
      <p><%= message.infomation %></p>
    <% end %>
  </div>
  <p>My Money Pledged: <%= current_user.pledges.sum(:amount) %></p>
<% end %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<h3 class="ptitle"><%= @project.title %></h3>

<% if current_user && current_user.pledges.exists?(project_id: @project.id) %>
  you backed this project
<% end %>
<p class="projectowner">Created by: <%= @project.user.name %></p>
<p class="pdescription"><%= @project.description %></p>
<p class="pstardate">Start Date:   <%= @project.startdate %></p>



<% newtime = @project.startdate > DateTime.now() ? @project.startdate : DateTime.now()%>
<p><strong>Days left: <%= ((@project.finishdate - newtime)/1.day).round %><strong></p>
<strong>$<p id= "earned<%= @project.id %>"><%= @project.pledges.sum(:amount)  %></p> pledged of $<%= @project.goal%> goal</strong>
<br>
<fieldset class="tag fieldset">Tags: <%= @project.tags.map{|tag| tag.title}.join('#') %></fieldset>
<% @project.rewards.each do |reward| %>
<fieldset class="reward fieldset">
  <p>Reward description: <%= reward.description %></p>
  <% if current_user && @project.user_id != current_user.id %>
    <button type="button" name="reward" class="<%= current_user.id %>" id= "<%= reward.id %>|<%= @project.id %>">pledge <%= reward.price %></button>
  <% else %>
    Reward Price: <%= reward.price %>
  <% end %>
</fieldset>
<% end %>
<br><br><br>

<div class="message_box">
  <% @messagesprojects.each do |message|%>
    <p>Comment: <%= message.infomation %></p>
  <% end %>
</div>

<% if !current_user || @project.user_id == current_user.id %>
<% else %>
  <fieldset>
    <form id="messagereview" action="index.html" method="post">
      Message:<br>
      <textarea id="rd" name="message" data-project=<%= @project.id%> data-user=<%= @project.user_id%>></textarea>
      <input type="submit" name="name">
    </form>
  </fieldset>
  <fieldset>
    <form id="messagereviewuser" action="index.html" method="post">
      Message:Owner<br>
      <textarea id="rdr" name="message" data-project=<%= @project.id%> data-user=<%= @project.user_id%>></textarea>
      <input type="submit" name="name">
    </form>
  </fieldset>
<% end %>

app/views/users/new.html.erb
<div class="text-center" style="padding:50px 0">
  <div class="logo">Crowdfunder</div>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="errors_messages">
          <h2>Form is invalid!</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><% message %>
              <% end %>
            </ul>
          </div>
          <% end %>

        <ul class="form1">
          <div class="form-group">
            <%= f.label '' do %>
            Name<span class="required">**********************</span>
            <% end %>
            <%= f.text_field :name %>
          </div>

          <div class="form-group">
            <%= f.label '' do %>
            Email<span class="required">**********************</span>
            <% end %>
            <%= f.email_field :email %>
          </div>

          <div class="form-group">
            <%= f.label '' do %>
            Password<span class="required">*****************</span>
            <% end %>
            <%= f.password_field :password %>
          </div>

          <div class="form-group">
            <%= f.label '' do %>
            Password confirmation<span class="required">*</span>
            <% end %>
            <%= f.password_field :password_confirmation %>
          </div>

          <div class="form-group">
            <%= f.submit %>
          </div>
        </ul>

    <% end %>

  </div>
</div>

<style>
body {
  background-color: orange;
}
</style>